
		const TowerTemplate* towerTemplate = Factory<TowerTemplate,Tower>::getTemplate(1);
		buildTower(towerTemplate,getMap()->getCase(2,0));
		buildTower(towerTemplate,getMap()->getCase(4,0));
		buildTower(towerTemplate,getMap()->getCase(2,1));
		buildTower(towerTemplate,getMap()->getCase(4,1));
		buildTower(towerTemplate,getMap()->getCase(2,2));
		buildTower(towerTemplate,getMap()->getCase(4,2));
		buildTower(towerTemplate,getMap()->getCase(5,2));
		buildTower(towerTemplate,getMap()->getCase(6,2));
		buildTower(towerTemplate,getMap()->getCase(2,3));
		buildTower(towerTemplate,getMap()->getCase(6,3));
		buildTower(towerTemplate,getMap()->getCase(7,3));
		buildTower(towerTemplate,getMap()->getCase(8,3));
		buildTower(towerTemplate,getMap()->getCase(2,4));
		buildTower(towerTemplate,getMap()->getCase(3,4));
		buildTower(towerTemplate,getMap()->getCase(4,4));
		buildTower(towerTemplate,getMap()->getCase(6,4));
		buildTower(towerTemplate,getMap()->getCase(7,4));
		buildTower(towerTemplate,getMap()->getCase(8,4));
		buildTower(towerTemplate,getMap()->getCase(4,5));
		buildTower(towerTemplate,getMap()->getCase(6,5));
		buildTower(towerTemplate,getMap()->getCase(7,5));
		buildTower(towerTemplate,getMap()->getCase(8,5));
		buildTower(towerTemplate,getMap()->getCase(4,6));
		buildTower(towerTemplate,getMap()->getCase(6,6));
		buildTower(towerTemplate,getMap()->getCase(7,6));
		buildTower(towerTemplate,getMap()->getCase(8,6));
		buildTower(towerTemplate,getMap()->getCase(4,7));
		buildTower(towerTemplate,getMap()->getCase(6,7));
		buildTower(towerTemplate,getMap()->getCase(7,7));
		buildTower(towerTemplate,getMap()->getCase(8,7));
		towerTemplate = towerTemplate->subTemplates.front();
		buildTower(towerTemplate,getMap()->getCase(4,7));
		buildTower(towerTemplate,getMap()->getCase(6,7));
		buildTower(towerTemplate,getMap()->getCase(7,7));
		buildTower(towerTemplate,getMap()->getCase(8,7));